### ISSUE TITLE
Allow to delete packages

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-syson/.eclipsefdn#4]
Hello, I would like to have the rights to delete packages deployed in github artifacts repository.
for exemple I would like to delete https://github.com/eclipse-syson/syson/packages/2020181/options but I don't have the rights for that.
I don't find how to do it in otterdog. Could you help me on that please?

**Comment by netomi** [comment]
I have deleted all the packages, only an org owner can do that, so I cant grant you that permission.

The last action failed as the packages already existed and the action could not overwrite them?

**Comment by AxelRICHARD** [comment]
Ok thank you! Yes this is the first release of syson, and I failed my first deploy.
On the second one, the action seems not being able to overwrite already deployed packages.

**Comment by netomi** [comment]
ok then fingers crossed for the next run

**Comment by AxelRICHARD** [comment]
Failed again :(

**Comment by netomi** [comment]
I am not sure about the write-all setting, but this documentation outlines the necessary things for publishing maven packages to GitHub: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

**Comment by netomi** [comment]
I would add

    permissions:
      contents: read
      packages: write

to the build job

**Comment by netomi** [comment]
maybe its also related to that: https://github.com/actions/setup-java/issues/79

**Comment by netomi** [comment]
the setup-java action will automatically create a settings.xml file which might overwrite your own version. You probably have to add the github repository to your own settings.xml and instruct setup-java to not overwrite the file.

**Comment by AxelRICHARD** [comment]
Thank you, I will try that very sson.

**Comment by netomi** [comment]
you could deploy in a run where you did not specify your custom settings.xml, then the other artifacts could not be referenced. So the generated settings.xml must contain something that is needed. The overwrite setting is not the problem I guess.

**Comment by AxelRICHARD** [comment]
Yes I tried that in my last commit but it fails after deploying 6 packages.
Could you delete them again please? I'm very sorry to bother you with that.

**Comment by netomi** [comment]
sure

**Comment by netomi** [comment]
deleted the packages, I would put the content in your custom settings.xml into the pom.xml and then you do not need to load it, maybe worth a try.

**Comment by netomi** [comment]
ah the problem is this:

    <server>
      <id>github</id>
      <username>${env.USERNAME}</username>
      <password>${env.PASSWORD}</password>
    </server>

this overrides the GITHUB_TOKEN in the generated settings.xml and thats why authentication does not work

**Comment by netomi** [comment]
these are the defaults from the setup-java action:

![image](https://github.com/eclipse-syson/.eclipsefdn/assets/1048055/e52f7a82-c137-4c95-ba5d-3a855bdd828d)

**Comment by AxelRICHARD** [comment]
May be, but in my deploy step in https://github.com/eclipse-syson/syson/blob/main/.github/workflows/build.yml#L91 I do not use the settings.xml file.
I've added it a few commits ago, after the first deploy failed.
Nevertheless, I will remove it.

**Comment by netomi** [comment]
The step before you do that:

      - name: Build the backend
        env:
          USERNAME: ${{github.actor}}
          PASSWORD: ${{secrets.GITHUB_TOKEN}}
        run: mvn -U -B -e clean verify --settings settings.xml


then you override the username and password correctly and use the settings.xml

if you do the same with the publish it might also work

**Comment by AxelRICHARD** [comment]
Ok I'm gonna try that

**Comment by AxelRICHARD** [comment]
It's worse, It fails on the first package deployment: https://github.com/eclipse-syson/syson/actions/runs/7298809126/job/19890458720

**Comment by netomi** [comment]
I guess playing around with the settings.xml will lead to nowhere, I would really suggest to move the required parts into your pom.xml and get rid of it, you basically define additional repos where to download dependent artifacts from.

**Comment by AxelRICHARD** [comment]
Ok thank you, can you delete the packages once agin please?

**Comment by AxelRICHARD** [comment]
Hope you will be there this afternoon, because I think I might need you to delete the packages a few times more :)

**Comment by netomi** [comment]
deleted

**Comment by AxelRICHARD** [comment]
If you are not available this afternoon could you give me temporary rights so I could delete the packages by myself until 
 the deployment succeeds please?

**Comment by netomi** [comment]
I cant give you permissions, but I will be around.

**Comment by netomi** [comment]
when I worked on such release workflows, I usually tested them in a fork where I have full control, once that is working do it in the repo itself and adjust as needed.

**Comment by AxelRICHARD** [comment]
Could you delete all packages please?

**Comment by netomi** [comment]
deleted

**Comment by AxelRICHARD** [comment]
It's ok, all packages have been deployed! Thank you again for your patience and availability.

**Comment by netomi** [comment]
ok great. So the actual problem was the module definition in the parent pom?

**Comment by AxelRICHARD** [comment]
Honestly, I'm not sure after having made many changes. It is also possible that, since the beginning, it was only a github problem about the availability of a required maven package as it happens sometimes.
